import { Player } from './types';

export const SEEDED_PLAYERS: Player[] = [
  // Indian Players
  {
    id: 'p1',
    name: 'Virat Kohli',
    role: 'Batsman',
    nationality: 'Indian',
    basePrice: 200,
  },
  {
    id: 'p2',
    name: 'Rohit Sharma',
    role: 'Batsman',
    nationality: 'Indian',
    basePrice: 200,
  },
  {
    id: 'p3',
    name: 'Jasprit Bumrah',
    role: 'Bowler',
    nationality: 'Indian',
    basePrice: 200,
  },
  {
    id: 'p4',
    name: 'Ravindra Jadeja',
    role: 'All-Rounder',
    nationality: 'Indian',
    basePrice: 150,
  },
  {
    id: 'p5',
    name: 'MS Dhoni',
    role: 'Wicket-Keeper',
    nationality: 'Indian',
    basePrice: 200,
  },
  {
    id: 'p6',
    name: 'KL Rahul',
    role: 'Wicket-Keeper',
    nationality: 'Indian',
    basePrice: 150,
  },
  {
    id: 'p7',
    name: 'Shubman Gill',
    role: 'Batsman',
    nationality: 'Indian',
    basePrice: 100,
  },
  {
    id: 'p8',
    name: 'Mohammed Siraj',
    role: 'Bowler',
    nationality: 'Indian',
    basePrice: 100,
  },
  {
    id: 'p9',
    name: 'Hardik Pandya',
    role: 'All-Rounder',
    nationality: 'Indian',
    basePrice: 150,
  },
  {
    id: 'p10',
    name: 'Suryakumar Yadav',
    role: 'Batsman',
    nationality: 'Indian',
    basePrice: 150,
  },
  {
    id: 'p11',
    name: 'Axar Patel',
    role: 'All-Rounder',
    nationality: 'Indian',
    basePrice: 75,
  },
  {
    id: 'p12',
    name: 'Yuzvendra Chahal',
    role: 'Bowler',
    nationality: 'Indian',
    basePrice: 75,
  },
  // Overseas Players
  {
    id: 'p13',
    name: 'Pat Cummins',
    role: 'Bowler',
    nationality: 'Overseas',
    basePrice: 200,
  },
  {
    id: 'p14',
    name: 'Jos Buttler',
    role: 'Wicket-Keeper',
    nationality: 'Overseas',
    basePrice: 200,
  },
  {
    id: 'p15',
    name: 'David Warner',
    role: 'Batsman',
    nationality: 'Overseas',
    basePrice: 150,
  },
  {
    id: 'p16',
    name: 'Rashid Khan',
    role: 'Bowler',
    nationality: 'Overseas',
    basePrice: 200,
  },
  {
    id: 'p17',
    name: 'Glenn Maxwell',
    role: 'All-Rounder',
    nationality: 'Overseas',
    basePrice: 150,
  },
  {
    id: 'p18',
    name: 'Nicholas Pooran',
    role: 'Wicket-Keeper',
    nationality: 'Overseas',
    basePrice: 100,
  },
  {
    id: 'p19',
    name: 'Mitchell Starc',
    role: 'Bowler',
    nationality: 'Overseas',
    basePrice: 200,
  },
  {
    id: 'p20',
    name: 'Faf du Plessis',
    role: 'Batsman',
    nationality: 'Overseas',
    basePrice: 100,
  },
];
