INSERT INTO players (id, name, role, base_price, country)
VALUES
  (gen_random_uuid(), 'Ruturaj Gaikwad', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Dewald Brevis', 'Batsman', 200, 'Overseas'),
  (gen_random_uuid(), 'MS Dhoni', 'Wicket-Keeper', 200, 'Indian'),
  (gen_random_uuid(), 'Kartik Sharma', 'Wicket-Keeper', 200, 'Indian'),
  (gen_random_uuid(), 'Sarfaraz Khan', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Ayush Mhatre', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Urvil Patel', 'Wicket-Keeper', 200, 'Indian'),
  (gen_random_uuid(), 'Sanju Samson', 'Wicket-Keeper', 200, 'Indian'),
  (gen_random_uuid(), 'Aman Khan', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Shivam Dube', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Zak Foulkes', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Ramakrishna Ghosh', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Anshul Kamboj', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Jamie Overton', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Matthew Short', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Prashant Veer', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Khaleel Ahmed', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Rahul Chahar', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Shreyas Gopal', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Gurjapneet Singh', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Matt Henry', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Akeal Hosein', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Spencer Johnson', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Mukesh Choudhary', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Noor Ahmad', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Nathan Ellis', 'Bowler', 200, 'Overseas');
