INSERT INTO players (id, name, role, base_price, country)
VALUES
  (gen_random_uuid(), 'Abishek Porel', 'Wicket-Keeper', 200, 'Indian'),
  (gen_random_uuid(), 'David Miller', 'Batsman', 200, 'Overseas'),
  (gen_random_uuid(), 'Karun Nair', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Pathum Nissanka', 'Batsman', 200, 'Overseas'),
  (gen_random_uuid(), 'Sahil Parakh', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'KL Rahul', 'Wicket-Keeper', 200, 'Indian'),
  (gen_random_uuid(), 'Nitish Rana', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Prithvi Shaw', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Tristan Stubbs', 'Wicket-Keeper', 200, 'Overseas'),
  (gen_random_uuid(), 'Ben Duckett', 'Wicket-Keeper', 200, 'Overseas'),
  (gen_random_uuid(), 'Axar Patel', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Ajay Mandal', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Sameer Rizvi', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Ashutosh Sharma', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Madhav Tiwari', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Auqib Nabi', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Dushmantha Chameera', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Kyle Jamieson', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Kuldeep Yadav', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Mukesh Kumar', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'T Natarajan', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Lungi Ngidi', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Vipraj Nigam', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Mitchell Starc', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Tripurana Vijay', 'Bowler', 200, 'Indian');
