INSERT INTO players (id, name, role, base_price, country)
VALUES
  (gen_random_uuid(), 'Shubman Gill', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Anuj Rawat', 'Wicket-Keeper', 200, 'Indian'),
  (gen_random_uuid(), 'Tom Banton', 'Wicket-Keeper', 200, 'Overseas'),
  (gen_random_uuid(), 'Jos Buttler', 'Wicket-Keeper', 200, 'Overseas'),
  (gen_random_uuid(), 'Kumar Kushagra', 'Wicket-Keeper', 200, 'Indian'),
  (gen_random_uuid(), 'Sai Sudharsan', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'M Shahrukh Khan', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Jason Holder', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Glenn Phillips', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Rashid Khan', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Nishant Sindhu', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Manav Suthar', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Rahul Tewatia', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Washington Sundar', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Arshad Khan', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Ashok Sharma', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Gurnoor Brar', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Kulwant Khejroliya', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Mohammed Siraj', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Prasidh Krishna', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Kagiso Rabada', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Sai Kishore', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Ishant Sharma', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Luke Wood', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Jayant Yadav', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Prithvi Raj', 'Bowler', 200, 'Indian');