INSERT INTO players (id, name, role, base_price, country)
VALUES
  (gen_random_uuid(), 'Rishabh Pant', 'Wicket-Keeper', 200, 'Indian'),
  (gen_random_uuid(), 'Abdul Samad', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Akshat Raghuwanshi', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Ayush Badoni', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Matthew Breetzke', 'Batsman', 200, 'Overseas'),
  (gen_random_uuid(), 'Mukul Choudhary', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Himmat Singh', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Josh Inglis', 'Wicket-Keeper', 200, 'Overseas'),
  (gen_random_uuid(), 'Aiden Markram', 'Batsman', 200, 'Overseas'),
  (gen_random_uuid(), 'Nicholas Pooran', 'Wicket-Keeper', 200, 'Overseas'),
  (gen_random_uuid(), 'Wanindu Hasaranga', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Arshin Kulkarni', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Mitchell Marsh', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Shahbaz Ahmed', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Akash Singh', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Avesh Khan', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Mohammed Shami', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Mohsin Khan', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Anrich Nortje', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Prince Yadav', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Digvesh Rathi', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Manimaran Siddharth', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Arjun Tendulkar', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Naman Tiwari', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Mayank Yadav', 'Bowler', 200, 'Indian');