INSERT INTO players (id, name, role, base_price, country)
VALUES
  (gen_random_uuid(), 'Quinton de Kock', 'Wicket-Keeper', 200, 'Overseas'),
  (gen_random_uuid(), 'Danish Malewar', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Robin Minz', 'Wicket-Keeper', 200, 'Indian'),
  (gen_random_uuid(), 'Ryan Rickelton', 'Wicket-Keeper', 200, 'Overseas'),
  (gen_random_uuid(), 'Sherfane Rutherford', 'Batsman', 200, 'Overseas'),
  (gen_random_uuid(), 'Rohit Sharma', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Suryakumar Yadav', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Hardik Pandya', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Atharva Ankolekar', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Raj Bawa', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Corbin Bosch', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Will Jacks', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Mayank Rawat', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Naman Dhir', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Mitchell Santner', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Shardul Thakur', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Tilak Varma', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Ashwani Kumar', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Trent Boult', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Jasprit Bumrah', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Deepak Chahar', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'AM Ghazanfar', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Mayank Markande', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Mohd Izhar', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Raghu Sharma', 'Bowler', 200, 'Indian');