INSERT INTO players (id, name, role, base_price, country)
VALUES
  (gen_random_uuid(), 'Shreyas Iyer', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Priyansh Arya', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Pyla Avinash', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Harnoor Singh', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Prabhsimran Singh', 'Wicket-Keeper', 200, 'Indian'),
  (gen_random_uuid(), 'Vishnu Vinod', 'Wicket-Keeper', 200, 'Indian'),
  (gen_random_uuid(), 'Nehal Wadhera', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Azmatullah Omarzai', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Cooper Connolly', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Marco Jansen', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Musheer Khan', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Mitchell Owen', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Shashank Singh', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Marcus Stoinis', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Suryansh Shedge', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Arshdeep Singh', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Xavier Bartlett', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Yuzvendra Chahal', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Praveen Dubey', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Ben Dwarshuis', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Lockie Ferguson', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Harpreet Brar', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Vishal Nishad', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Vijaykumar Vyshak', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Yash Thakur', 'Bowler', 200, 'Indian');