INSERT INTO players (id, name, role, base_price, country)
VALUES
  (gen_random_uuid(), 'Riyan Parag', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Aman Rao', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Shubham Dubey', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Shimron Hetmyer', 'Batsman', 200, 'Overseas'),
  (gen_random_uuid(), 'Yashasvi Jaiswal', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Dhruv Jurel', 'Wicket-Keeper', 200, 'Indian'),
  (gen_random_uuid(), 'Lhuan-dre Pretorius', 'Wicket-Keeper', 200, 'Overseas'),
  (gen_random_uuid(), 'Ravi Singh', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Vaibhav Sooryavanshi', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Donovan Ferreira', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Ravindra Jadeja', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Dasun Shanaka', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Sam Curran', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Jofra Archer', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Brijesh Sharma', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Nandre Burger', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Tushar Deshpande', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Kwena Maphaka', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Adam Milne', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Sushant Mishra', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Vignesh Puthur', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Ravi Bishnoi', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Sandeep Sharma', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Kuldeep Sen', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Yash Raj Punja', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Yudhvir Singh', 'Bowler', 200, 'Indian');