INSERT INTO players (id, name, role, base_price, country)
VALUES
  (gen_random_uuid(), 'Rajat Patidar', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Jordan Cox', 'Wicket-Keeper', 200, 'Overseas'),
  (gen_random_uuid(), 'Tim David', 'Batsman', 200, 'Overseas'),
  (gen_random_uuid(), 'Virat Kohli', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Devdutt Padikkal', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Phil Salt', 'Wicket-Keeper', 200, 'Overseas'),
  (gen_random_uuid(), 'Jitesh Sharma', 'Wicket-Keeper', 200, 'Indian'),
  (gen_random_uuid(), 'Jacob Bethell', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Kanishk Chouhan', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Venkatesh Iyer', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Vihaan Malhotra', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Mangesh Yadav', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Krunal Pandya', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Romario Shepherd', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Abhinandan Singh', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Satvik Deswal', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Jacob Duffy', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Josh Hazlewood', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Bhuvneshwar Kumar', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Vicky Ostwal', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Rasikh Salam', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Suyash Sharma', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Swapnil Singh', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Nuwan Thushara', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Yash Dayal', 'Bowler', 200, 'Indian');