INSERT INTO players (id, name, role, base_price, country)
VALUES
  (gen_random_uuid(), 'Ishan Kishan', 'Wicket-Keeper', 200, 'Indian'),
  (gen_random_uuid(), 'Salil Arora', 'Wicket-Keeper', 200, 'Indian'),
  (gen_random_uuid(), 'Travis Head', 'Batsman', 200, 'Overseas'),
  (gen_random_uuid(), 'Heinrich Klaasen', 'Wicket-Keeper', 200, 'Overseas'),
  (gen_random_uuid(), 'Ravichandran Smaran', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Aniket Verma', 'Batsman', 200, 'Indian'),
  (gen_random_uuid(), 'Abhishek Sharma', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Brydon Carse', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Harsh Dubey', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Krains Fuletra', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Liam Livingstone', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Kamindu Mendis', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Nitish Kumar Reddy', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Harshal Patel', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Shivam Mavi', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Shivang Kumar', 'All-Rounder', 200, 'Indian'),
  (gen_random_uuid(), 'Jack Edwards', 'All-Rounder', 200, 'Overseas'),
  (gen_random_uuid(), 'Amit Kumar', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Pat Cummins', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Praful Hinge', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Eshan Malinga', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'David Payne', 'Bowler', 200, 'Overseas'),
  (gen_random_uuid(), 'Sakib Hussain', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Onkar Tarmale', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Jaydev Unadkat', 'Bowler', 200, 'Indian'),
  (gen_random_uuid(), 'Zeeshan Ansari', 'Bowler', 200, 'Indian');